[project]
name = "yvora-ft"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
  "streamlit==1.36.0",
  "gspread==6.1.2",
  "google-auth==2.33.0",
  "pandas==2.2.2",
  "setuptools",
  "wheel",
]
